### ISSUE TITLE
Are overwrite and skipCache parameters the same?

### ISSUE THREAD

**Issue by longtimeago** [download-maven-plugin/download-maven-plugin#80]
``` java
    /**
     * Flag to overwrite the file by redownloading it
     */
    @Parameter(property = "download.overwrite")
    private boolean overwrite;
```

and 

``` java
    /**
     * Download file without polling cache
     */
    @Parameter(defaultValue = "false")
    private boolean skipCache;
```

IMO, these parameters are doing the same?
Am I wrong?

**Comment by mickaelistria** [comment]
They are not intended to do the same:
* `overwrite=true` means that if the target file pre-exists at the expected target-location (usually `${download.output.directory}/${download.output.filename}`) for the current plugin execution, then the pre-existing file will be overwritten and replaced anyway; whereas default `overwrite=false` will entirely skip all the execution if the target file pre-exists and marches specifiecation (name, signatures...).
* `skipCache` means that the download operation will not look in the global cache to resolve the file to download, and will directly process with the download and won't store this download in the cache. It's recommended for url that have "volatile" content.

**Comment by longtimeago** [comment]
@mickaelistria now it's clear, thanks!
Would be nice to have this description somewhere in the doc/code

**Comment by mickaelistria** [comment]
This answer would actually be a better Javadoc for those settings.

**Comment by jlanza** [comment]
I have the following code in my pom file and the files are not getting downloaded:
```
				<executions>
					<execution>
						<id>data</id>
						<phase>process-resources</phase>
						<goals>
							<goal>wget</goal>
						</goals>
						<configuration>
							<url>MYURL</url>
							<outputDirectory>${project.build.outputDirectory}/etc/vocabularies</outputDirectory>
							<!-- <outputDirectory>${basedir}/src/main/resources/etc/vocabularies</outputDirectory> -->
							<outputFileName>fiesta-iot.owl</outputFileName>
							<overwrite>true</overwrite>
							<skipCache>true</skipCache>
						</configuration>
					</execution>
```
I'm using `mvn process-resources` but the resources are not overriden. Is it really working?

**Comment by mickaelistria** [comment]
Have you tried version 1.3.1-SNAPSHOT ?

**Comment by jlanza** [comment]
I'm trying now, but some problems with configuration.  PKIX path building failed error or something.

**Comment by jlanza** [comment]
Now that I have fixed the certificate issue I get the following
Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.3.1-SNAPSHOT:wget (data) on project myproject: Execution data of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.3.1-SNAPSHOT:wget failed: java.lang.ClassNotFoundException: com.googlecode.download.maven.plugin.internal.CachedFileEntry -> [Help 1]

**Comment by ninckblokje** [comment]
@jlanza You might have already fixed this, but the solution for java.lang.ClassNotFoundException: com.googlecode.download.maven.plugin.internal.CachedFileEntry is to delete the .m2/repository/.cache/download-maven-plugin directory

**Comment by deki** [comment]
Could you please offer a clean goal for that or to some try/ catch for it? After updating from 1.3 to 1.4 we're facing this error and would have to visit multiple Jenkins build nodes to fix that.

**Comment by mickaelistria** [comment]
FYI, I think that all active contributors to this project are busy with higher priority stuff; and won't have cycles to implement what you want.
Best way to make things happen is to provide the necesary changes as pull requests.
And if at some point, some people feel more dependent on this project than current committers, I'd gladly grow the team to include more people as committers.

**Comment by hieplq** [comment]
two option should independence. my use case:
i download file from https://host/releae-version/file.ext to project/lib/file.ext

so each time i release, i just update url to new releae-version don't need update my classpath and dependence stuff
example i have new release if i build on old workspace i get below issue:
1. because project/lib/file.ext already exists, it don't update (cache still get new version)
2. i add download.overwrite=true but i get exception "java.nio.file.FileAlreadyExistsException" (detail see quote at end of post)
3. i have to add <skipCache>true</skipCache> to resolve it. but i don't want it skipCache, just update my file from cache or upstream

> [ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget (download-db-seed-pg) on project org.adempiere.server.feature: IO Error: /mnt/data/1Dev/project/native/idempiere-dev-11/org.adempiere.server-feature/data/seed/Adempiere_pg.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget (download-db-seed-pg) on project org.adempiere.server.feature: IO Error
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: IO Error
    at com.googlecode.download.maven.plugin.internal.WGet.execute (WGet.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.nio.file.FileAlreadyExistsException: /mnt/data/1Dev/project/native/idempiere-dev-11/org.adempiere.server-feature/data/seed/Adempiere_pg.jar
    at sun.nio.fs.UnixCopyFile.copy (UnixCopyFile.java:573)
    at sun.nio.fs.UnixFileSystemProvider.copy (UnixFileSystemProvider.java:254)
    at java.nio.file.Files.copy (Files.java:1294)
    at com.googlecode.download.maven.plugin.internal.WGet.execute (WGet.java:279)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.adempiere.server.feature

**Comment by longtimeago** [comment]
@hieplq it seems like you've faces with https://github.com/maven-download-plugin/maven-download-plugin/issues/194 which should be fixed in the next release :)

**Comment by longtimeago** [comment]
initial claim was fixed in https://github.com/download-maven-plugin/download-maven-plugin/pull/200
thus, closing
